/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { SemaphoreCore } from "./SemaphoreCore";
export type { SemaphoreGroups } from "./SemaphoreGroups";
