/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ISemaphoreCore } from "./ISemaphoreCore";
export type { ISemaphoreGroups } from "./ISemaphoreGroups";
export type { IVerifier } from "./IVerifier";
