/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mockErc721Sol from "./MockERC721.sol";
export type { mockErc721Sol };
import type * as verifier16Sol from "./Verifier16.sol";
export type { verifier16Sol };
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { MockERC1155 } from "./MockERC1155";
export type { Zmorpheus } from "./Zmorpheus";
